### ISSUE TITLE
Hosting Graval based FTP server in a Docker container on MacOS

### ISSUE THREAD

**Issue by mclark4386** [yob/graval#18]
So I've made a custom FTP server using graval and it works great on it's own, but I need it to run in a docker container. I have set the pasvMin/MaxPorts  and then exposed those both in the image and using docker compose, however, the server/client keep trying to connect on ports outside of that range when I try to STOR a file from a standard ftp client. I have debugged enough to know that it is creating an active socket instead of a passive one for this type of command. Perhaps, it's my lack of understanding of FTP, but any ideas how I can get the server to force the use of a certain set of ports so I can make this work in a container/behind a firewall? I'm happy to make changes and a pull request, but would like guidance as to where/what the change would need to be made to make it work well for everyone, not just me. Thanks!

For reference, here is my server set up code:

```
	opts := &graval.FTPServerOpts{
		Factory:     factory,
		ServerName:  "customFTP",
		PasvMinPort: 60000,
		PasvMaxPort: 60100,
		Port:        21,
		Hostname:    "0.0.0.0",
	}
	ftpServer := graval.NewFTPServer(opts)
```

And here is my docker-compose file:

```
version: "3.1"

services:
  ftp:
    image: myreg/testing/go/customftp:latest
    environment:
      FTP_USER: test
      FTP_PASS: 1234
    ports:
      - "21:21"
      - "20:20"
      - "60000-60100:60000-60100"
```
